### ISSUE TITLE
Sementation Fault

### ISSUE THREAD

**Issue by czgdp1807** [andim/scipydirect#11]
Code
```python
import numpy as np
import scipydirect
from scipydirect import minimize

print(scipydirect.__file__)

def obj(x):
    return (x**2).sum()

bounds = [[-3.0, 3.0], [0.5, 5.0]]
res = minimize(obj, bounds=bounds)
print(res)
```

Output
```
/home/czgdp1807ssd/scipy_project/scipydirect/scipydirect/__init__.py
Segmentation fault
```

Python - 3.9.5, 3.7.6
GCC - 9.3.0

**Comments**

It seems like the problem is with tool used to convert `direct.pyf` to `direcmodule.c` because, with Python - 3.7.10 and GCC - 7.5.0, the above code works fine. 

ping @andim

**Comment by czgdp1807** [comment]
It seems like the problem is with GCC version and not python version.

**Comment by czgdp1807** [comment]
The bug is somewhere below in `directmodule.c` generated file.
```c
/*callfortranroutine*/
    if ((setjmp(cb_fcn_in_direct__user__routines_jmpbuf))) {
      f2py_success = 0;
    } else {
         // In the below line one of the parameters is null I believe which is causing segfault.
        (*f2py_func) (fcn_cptr,x,&n,&eps,&maxf,&maxt,&fmin,l,u,&algmethod,&ierror,logfilename,&fglobal,&fglper,&volper,&sigmaper,iidata,&iisize,ddata,&idsize,cdata,&icsize,&disp,slen(logfilename));
    }
```

**Comment by andim** [comment]
I think this issue has resolved itself with the successful inclusion of direct into `scipy` 1.9. Thanks again for helping making direct part of scipy proper.
