### ISSUE TITLE
objective_wrap function catches exceptions too broadly

### ISSUE THREAD

**Issue by nmusolino** [andim/scipydirect#13]
Within `minimize()`, the local [`_objective_wrap` function](https://github.com/andim/scipydirect/blob/e553380563e6d39a60aa37d911284983ad8b3620/scipydirect/__init__.py) catches exceptions thrown by the user-provided objective function:
```
        try:
            return func(x, *args), 0
        except:
            return np.nan, 1
```

The bare `except:` clause catches all exceptions, including `KeyboardInterrupt` and `SystemExit`.  This is generally [not recommended](https://stackoverflow.com/questions/54948548/what-is-wrong-with-using-a-bare-except), as in this case it can prevent the user from interrupting their application within `minimize()`.

It would be more conventional to use `except Exception` to catch user-thrown exceptions, while allowing `KeyboardInterrupt` to stop the Python processn as the user intends.

**Comment by andim** [comment]
Thanks for the merge request, indeed this is a more reasonable way to catch the Exceptions. :)
