### ISSUE TITLE
WARNING : Capacity of array S in DIRDoubleInsert reached. Increase maxdiv.

### ISSUE THREAD

**Issue by tinutjoy** [andim/scipydirect#3]
I am getting this warning " 
WARNING : Capacity of array S in DIRDoubleInsert reached. Increase maxdiv.
This means that there are a lot of hyperrectangles with the same function value at the center. We suggest to use our modification instead (Jones = 1)". What is the modification algo,? How can I use it?

Thanks,
Tinu

**Comment by andim** [comment]
Hi Tinu,
You should be able to change the algorithm that is used by setting the `algmethod` keyword argument to 1. I do not know the underlying Fortran code enough to be able to say what precisely is causing this warning. Feel free to take a look yourself at the source code in the src directory.

HTH,
Andreas

**Comment by tinutjoy** [comment]
Hi Andrea,

I will check it. I am closing the issue. Thank you.

Cheers,
Tinu
