### ISSUE TITLE
'NoneType' object is not callable

### ISSUE THREAD

**Issue by theSha1do1w** [andim/scipydirect#4]
when i try on the demo:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-5c1d66e2d55f> in <module>()
     17 
     18 bounds = [(-3, 3), (-2, 2)]
---> 19 res = minimize(obj, bounds)
     20 
     21 #

~\Miniconda3\lib\site-packages\scipydirect-1.3-py3.6.egg\scipydirect\__init__.py in minimize(func, bounds, nvar, args, disp, eps, maxf, maxT, algmethod, fglobal, fglper, volper, sigmaper, **kwargs)
    252                         ddata,
    253                         cdata,
--> 254                         disp
    255                         )
    256 

TypeError: 'NoneType' object is not callable

**Comment by theSha1do1w** [comment]
and i get this error when i import the scipydirect:
Fortran code not compiled, module not functional

**Comment by andim** [comment]
Both errors have the same reason: the Fortran extension has not been
properly installed. Please make sure you have the relevant requirements on
your computer,
In particular a Fortran compiler, and then reinstall the package.
