### ISSUE TITLE
'NoneType' object is not callable

### ISSUE THREAD

**Issue by licheng0794** [andim/scipydirect#5]
I install scipydirect in spyder and directly run the example given. The error message is 

  File "C:\Users\XXX\AppData\Local\Continuum\anaconda2\lib\site-packages\scipydirect\__init__.py", line 254, in minimize
    disp

TypeError: 'NoneType' object is not callable

**Comment by andim** [comment]
The reason is a missing fortran installation. Please make sure you first install fortran before installing scipydirect. See issue #4
