### ISSUE TITLE
"Fortran code not compiled" Error Python 3.8

### ISSUE THREAD

**Issue by ldv1** [andim/scipydirect#8]
I managed to compile scipydirect with python 3.6 and it runs successfully; with python 3.8 on the other hand, I get the infamous "Fortran code not compiled" error message, which surprises me; question: have you tried to run scipydirect on python 3.8?

**Comment by andim** [comment]
I just tried installing and importing the package in a conda python 3.8 environment and it worked without issues for me. The behavior you describe is indeed surprising as the existence of the fortran compiler should not depend n python version. Are you using any sort of environment manager that might change that?

**Comment by ldv1** [comment]
Thanks for your prompt feedback!
I do not know the cause of the problem right now.
Which Fortran are you using?

**Comment by andim** [comment]
I am using gfortran version 9.3.0. In the 3.8 environment can you succesfully run fortran from the command line?

**Comment by ldv1** [comment]
Yes, I can run fortran from the command line. If I compare the outputs of the compilation process with e.g. tkdiff, Python 3.6 versus Python 3.8 environment, there are only minor differences, due to the different compilers (Fortran 4.9 versus Fortran 7.5), so it puzzles me why I get the "Fortran code not compiled" error message in the Python 3.8 environment.

**Comment by ldv1** [comment]
I used pip3 install --user ./ and it worked! (instead of python3 setup.py --prefix=./).
